[build]
  publish = "public"
  command = "node generate-pages-metadata.js && echo 'No build step required'"

# Remove the redirects for the functions
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
