[build]
  publish = "public"
  command = "node generate-pages-metadata.js && echo 'No build step required'"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/generate-sitemap"
  status = 200

[[redirects]]
  from = "/metadata-test"
  to = "/.netlify/functions/serve-metadata"
  status = 200
